# The name of your workflow
name: Simple CI

# Trigger -> Events
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Tasks to do when Trigger is ON
jobs: 
  # Task Name
  test: 
    # (Runner) The type of machine to run the job on -> VM on Github
    runs-on: ubuntu-latest
    steps:
      # Load my code from repo into server
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # Install Libraries
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Code Linting with Ruff
      - name: Lint with Ruff
        run: ruff check

      # Run PyTest
      - name: Run Tests
        run: 
          python -m pytest -v    # v = verbose

  deploy:
    # Not works until Test is succeded
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: |
          echo "🚀 Starting deployment..."
          echo "Environment: Production"
          echo "Commit: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"
          echo "✅ Deployment completed successfully!"
